### ISSUE TITLE
Support custom authentication methods

### ISSUE THREAD

**Issue by edandersen** [edandersen/core-admin#2]
Should be able to provide an Action to execute in addition to the Role based auth for more flexibility.

**Comment by sahajquinci** [comment]
I tried to use CoreAdmin adding a role from the custom authentication explained in the guide at the following link:

 https://jasonwatmore.com/post/2019/10/16/aspnet-core-3-role-based-authorization-tutorial-with-example-api

I get rejected with 401 because     AuthorizationFilterContext doesn't have my custom roles and users.

**Comment by edandersen** [comment]
Implemented in 1.3.0.
