### ISSUE TITLE
Translations support

### ISSUE THREAD

**Issue by Sl4vP0weR** [edandersen/core-admin#5]
Ability to add translations for: column names, tables, buttons, filter conditions, Core Admin label.
Ability to set a custom path to CoreAdmin.

**Comment by edandersen** [comment]
Split the custom path request into #6

**Comment by Brouilles** [comment]
II have tried to add localization. But don't work. No error, just the text rest the same. If anyone have an idea. (Maybe because it is a package, so different to normal integration https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.0#resource-file-naming-1)

Fork / Branch here: https://github.com/Brouilles/core-admin/tree/localization

**Comment by Brouilles** [comment]
Found this https://stackoverflow.com/questions/42044458/asp-net-core-localized-resource-in-separate-assembly
But `IStringLocalizer` don't seems available for .net core 3.1.

**Comment by Brouilles** [comment]
Got it. Works with this commit https://github.com/Brouilles/core-admin/commit/92fa6b7056bc9f3164f75f9fa49159df75648878
Can't continue now. Bug when I have free time, I implement it in my fork, after squash it and make a pull request. 
After, you accept or not @edandersen!

**Comment by Brouilles** [comment]
Not satisfied with my code (see branch https://github.com/Brouilles/core-admin/tree/localization). In stand by for the moment.

**Comment by edandersen** [comment]
Added in 2.6.0!
