### ISSUE TITLE
if (!Model.Rows.Any() causes re-execution of the select statement against SqlServer Table

### ISSUE THREAD

**Issue by Dredy** [edandersen/core-admin#84]
In the partial _Grid.cshtml there is an  if statement, that check if there any rows, in order to display an "Empty table message"

https://github.com/edandersen/core-admin/blob/93370854f40bfa1fa94d9d2915ce2c7db4ab4fe6/src/DotNetEd.CoreAdmin/Views/Shared/MvcGrid/_Grid.cshtml#L148

The Model.Rows.Any() causes the re-execution of the query against the database.
After commenting the section the database will be called only one time.

I will search a better way to expose the Zero rows message.

**Comment by edandersen** [comment]
Better to report this to the MvcGrid project. Not going to fork the views from their templates.

If you are worried about hyperoptimisation of queries I highly suggest building a custom admin panel - this is just a quick tool.

________________________________
From: Dredy ***@***.***>
Sent: Sunday, April 16, 2023 8:44:34 PM
To: edandersen/core-admin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [edandersen/core-admin] if (!Model.Rows.Any() causes re-execution of the select statement against SqlServer Table (Issue #84)


In the partial _Grid.cshtml there is an if statement, that check the number of rows, in order to display an "Empty table message"

https://github.com/edandersen/core-admin/blob/93370854f40bfa1fa94d9d2915ce2c7db4ab4fe6/src/DotNetEd.CoreAdmin/Views/Shared/MvcGrid/_Grid.cshtml#L148

The Model.Rows.Any() causes the re-execution of the query against the database.
After commenting the section the database will be called only one time.

I will search a better way to expose the Zero rows message.

**Comment by Dredy** [comment]
> Better to report this to the MvcGrid project. Not going to fork the views from their templates. If you are worried about hyperoptimisation of queries I highly suggest building a custom admin panel - this is just a quick tool.

I know that the View is on the Mvc.Grid source, but Your DLL contains that View.
This is just a quick tool, but it can be improved.

btw: Peace and love, it's not necessary to be so rude in your replies.
